### ISSUE TITLE
 No kernel image is available for execution on the device

### ISSUE THREAD

**Issue by LeiaLi** [princeton-vl/RAFT#117]
**I downloaded the _download_models.sh_ and run _python demo.py --model=models/raft-things.pth --path=demo-frames_. However, there is no *.jeg image in demo-frames file. The details are:**
Traceback (most recent call last):
  File "demo.py", line 75, in <module>
    demo(args)
  File "demo.py", line 62, in demo
    flow_low, flow_up = model(image1, image2, iters=20, test_mode=True)
  File "/workspace/lhy/anaconda3/envs/raft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "core/raft.py", line 111, in forward
    cnet = self.cnet(image1)
  File "/workspace/lhy/anaconda3/envs/raft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "core/extractor.py", line 178, in forward
    x = self.relu1(x)
  File "/workspace/lhy/anaconda3/envs/raft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/lhy/anaconda3/envs/raft/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 102, in forward
    return F.relu(input, inplace=self.inplace)
  File "/workspace/lhy/anaconda3/envs/raft/lib/python3.7/site-packages/torch/nn/functional.py", line 1117, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**How to solve this?** Thanks!

**Comment by Tsugikuni-Yoriichi** [comment]
@zachteed 
I have the same problem. When I run the code you mentioned above, the result is True.
I am using a 3060Ti with cuda version 11.4.

**Comment by Tsugikuni-Yoriichi** [comment]
@LeiaLi  I have solved the problem. It is because the version of pytorch and cudatoolkit. I am using 3060ti with cuda11.4. And I installed the python packages with: 
conda install pytorch=1.9.0 torchvision cudatoolkit=11.1 matplotlib tensorboard scipy opencv -c pytorch
You should have met the same problem. Try to find the correct version of pytorch and cudatoolkit according to your cuda version.
