### ISSUE TITLE
Cuda out of memory (when using many frames)

### ISSUE THREAD

**Issue by Wazaki-Ou** [princeton-vl/RAFT#43]
Hi there

I know that a similar issue has been raised before and I already took a look at it. The solution of modifying that line actually helped with images of size1920*1080. So I made few modifications on the demo.py to read images and save the optical flow viz and it works fine with 20 images. However, when I try on a bigger number (300 images), I get the Cuda out of memory error code again. I thought that using `with torch.no_grad():` allowed freeing the memory used by pytorch every time. 

The error happens specifically in this line of code: `return padder.pad(images)[0]`

I even modified the code so that `load_image_list()` would be called for every 10 images inside a loop so that I could use the returned values as input for to model extract the flow for batches of 10 images one batch at a time. But I still get an out of memory error. I was sure this would solve the issue since I was able to work with 20 images before. What am I missing?

Thanks a lot !!

**Comment by zachteed** [comment]
The original demo script was only meant for small sequences of frames. You were running out of memory because all images were being placed on the gpu as once.

I modified demo.py so it will now work fine with an arbitrary number of frames similar to the evaluation scripts.

**Comment by Wazaki-Ou** [comment]
Thanks a lot !! That solved the issue.
